### ISSUE TITLE
11.0 barcodes_generator_abstract

### ISSUE THREAD

**Issue by ghost** [OCA/stock-logistics-barcode#156]
After a module upgrade the nomeclature is set to default values.

**Comment by pedrobaeza** [comment]
Which nomenclature? Can you specify the field in the model?

**Comment by ghost** [comment]
I use the product barcode.
The barcode pattern is set back to *. and encoding to any

**Comment by legalsylvain** [comment]
OK. You're talking about this pattern defined here : 
https://github.com/odoo/odoo/blob/11.0/addons/barcodes/data/barcodes_data.xml#L7

this is a data set by Odoo in barcodes module, not by the module barcodes_generator_abstract.

you have to create a new pattern and use it. The one you are using will be updated during each update, because it is defined as updatable.

kind regards.
