### ISSUE TITLE
[RFC] Contributing an open source Android app for stock moving with barcode scanning to OCA

### ISSUE THREAD

**Issue by daramousk** [OCA/stock-logistics-barcode#165]
Hello,

I have been working on an Android application which at some point I would like to push to OCA https://github.com/daramousk/android-odoo-delivery.

The use case for such an application would be to perform stock moves on the go.

At this stage this is **heavily beta** and possible you will experience a lot of crashes. Basically at this stage there is a primitive UI that you can use to synchronize to your server, use the phone's camera to scan for stuff, search etc.

What I would like from this ticket is to do some proper requirements gathering as to what do we need from such an application, and what a proper interface would look like.

Your contributions are greatly appreciated.

Thanks

**Comment by legalsylvain** [comment]
Hi @daramousk. Thanks for sharing this work.

I work since 3 years on mobile apps (purchase and inventory). for the most mature module (inventory) the code is under OCA umbrella on version 8.0, https://github.com/OCA/stock-logistics-barcode/tree/8.0/mobile_app_inventory.

In a few words, it's a module that deploy web interface that are compatible with mobile device and it is used on production in GRAP and in Akretion customers. The technologies used are based on ionic, so I guess that making an app, based on that work is possible. (maybe with cordova, even if I didn't tried).
If yes, it could be great to have such design for your picking app. (one single source code for a web page AND the app (android, iOS)). What do you think ?

CC : @hparfr.

**Comment by daramousk** [comment]
@legalsylvain Perfect Sylvain thank you. I will keep reading this and see what I can incorporate.
