### ISSUE TITLE
[12.0] barcodes_generator_product can't generate unique barcodes

### ISSUE THREAD

**Issue by eLBati** [OCA/stock-logistics-barcode#250]
Steps:

 - Define a barcode rule with pattern `20.....{NNNDD}`, "base set manually" and model = products
 - Create a new product setting the defined rule and Barcode Base = 12345
 - Click "generate barcode" and get 2012345000001
 - Create another product with the same fields and click "generate barcode"

Get the same barcode: 2012345000001

@legalsylvain is this intended? Am I missing anything?

Thanks

**Comment by legalsylvain** [comment]
Hi @eLBati.
This module provides two ways to generate custom barcode : 
- one with a sequence autoincremented, 
- one with user providing custom base. (your choice here).
Well, in that case, if you give two identical bases to two products, the generated barcode will be the same. That's quit normal !

But this constraint should block such behaviour, don't you think ?

https://github.com/odoo/odoo/blob/12.0/addons/product/models/product.py#L158

**Comment by eLBati** [comment]
> But this constraint should block such behaviour, don't you think ?

Indeed, it is blocked by that constraint.

> Well, in that case, if you give two identical bases to two products, the generated barcode will be the same. That's quit normal !

Ok, it seems we are making different assumptions.

I was assuming to use the `12345` as the "Manufacturer code" defined by EAN-13.
So couldn't it be the code assigned to my company, fixed for all my products?

Also, in the use case described above, if the user is in charge to change the base code, what is the module supposed to generate?
Setting `Barcode Base` = `12346` the module generates `2012346000000`
Setting `Barcode Base` = `12347` the module generates `2012347000009`
Setting `Barcode Base` = `12348` the module generates `2012348000008`
and so on...

:thinking:

**Comment by legalsylvain** [comment]
> I was assuming to use the 12345 as the "Manufacturer code" defined by EAN-13.
So couldn't it be the code assigned to my company, fixed for all my products?

But if you do so, all the product will have the same EAN13 ? It is not what you want. If you want to have a fixed 12345 in the barcode, you can use ``0012345.....`` as the pattern and it will create ``001234500001x``, ``001234500002x``, ``001234500003x``, etc..

> Also, in the use case described above, if the user is in charge to change the base code, what is the module supposed to generate?
Setting Barcode Base = 12346 the module generates 2012346000000
Setting Barcode Base = 12347 the module generates 2012347000009
Setting Barcode Base = 12348 the module generates 2012348000008
and so on...

If you want such behaviour, you should use the same module, but "based on sequence", so it will be autoincremented.


Well, I'm not sure to understand your business needs. This module has been developped to generate barcode for product that doens't have, generating an "internal" EAN13 to be then used in stock, point of sale module, etc...
A typical use case is for retaillers that are selling products without barcode. We generate a barcode and then print it and put it on the product. So, the cashier can scan the barcode, without selecting product.

let me know if I'm not clear.

I personaly don't use the "manual base" because it is error prone, but it can be used, if you have an internal little code for your products. (that comes from another software, or a nomenclature like PLU for fruits and vegetable see : https://en.wikipedia.org/wiki/Price_look-up_code). But yes in any case, should be uniq.

kind regards.

**Comment by eLBati** [comment]
> If you want such behaviour, you should use the same module, but "based on sequence", so it will be autoincremented

Sorry, I don't want such a behaviour, I was describing what the module is doing in manual mode: it uses the base code, adds 5 zeros and control digit; it does not generate anything.

> A typical use case is for retaillers that are selling products without barcode. We generate a barcode and then print it and put it on the product. So, the cashier can scan the barcode, without selecting product

How should the module be configured for this use case?

Thanks

**Comment by legalsylvain** [comment]
Sorry, I don't understand what you don't understand :-)
Could you just enumerates the barcodes you want, and I'll say you how to configure this module.
Alternavely we can have a talk.
Kind regard.
