### ISSUE TITLE
[12.0] product_multi_ean does not seem to work

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/stock-logistics-barcode#271]
Hi, since product_multi_ean does not have instructions in the description I'm struggling to understand where to input multiple barcodes for a product.

I checked the runbot but cannot seem to find any multiple barcode feature, my dev says a table should be visible in the product model?

Can you please help me out and check if the module is working as inteded?

**Comment by francesco-ooops** [comment]
Is anyone else having issues with product_multi_ean?

**Comment by cscocca** [comment]
Yes I have the same issue [https://github.com/OCA/stock-logistics-barcode/issues/310](url). I created also a new issue because I did not see this

**Comment by pedrocs-exo** [comment]
I had the same problem so I decided to share my conclusions:

The EAN list is only visible on the Product Variants (product.product) form and not on the Products (product.template) form.

If you happen to have a system configuration without variants, things get can fun. If you access the products through the Invoicing menu, you'll see the EAN because Odoo will show you product.product items. But if you access them through the Sales menu, you won't, as Odoo displays product.template items.

Ideally, the module would present the EAN list on product.template in systems that don't use variants. Or at least the module description could include a small note regarding this matter.
