### ISSUE TITLE
Android mobile as scanner hardware?

### ISSUE THREAD

**Issue by svalencius** [OCA/stock-logistics-barcode#89]
Hi,
I'm trying to setup my android mobile phone as hardware scanner. Currently I'm planning to host sentinel.py on my VPS and use JuiceSSH or any other SSH app to connect to VPS and run sentinel.py inside.
I was wondering is there any other open sourced implementation which is more native for android? Like running sentinel directly in android as an app?

Also I noticed there's two types of _transition_type_: keyboard and scanner. Is there any difference if I use sentinel.py on SSH connection? I think like it can call barcode scanner on native application and I currently using android keyboard with barcode scanner who works like keyboard typing.

I have no experience how professional barcode readers works and what software they use.

It would be nice if someone share their experience with android scanners.

Thank you

**Comment by livingmine** [comment]
@simas068 Have you considered creating an API so that your android app can communicate with your Odoo instance to accomplish your goal? I haven't used this sentinel.py before and not really sure what are the benefits of using this approach against API approach though so i'm also curious on this topic.

**Comment by rousseldenis** [comment]
@svalencius What's the status of this ?
